# Generated by Django 5.0.2 on 2024-03-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
