# Generated by Django 5.0.2 on 2024-03-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0003_rename_userd_count_coupon_used_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
