# Generated by Django 5.0.2 on 2024-02-23 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
