# Generated by Django 5.0.2 on 2024-03-07 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_totp', '0002_auto_20190420_0723'),
        ('user_accounts', '0002_otpmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TOTPDevice',
            fields=[
                ('totpdevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='otp_totp.totpdevice')),
            ],
            options={
                'abstract': False,
            },
            bases=('otp_totp.totpdevice',),
        ),
    ]
