# Generated by Django 5.0.2 on 2024-03-31 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, max_length=600)),
                ('cat_image', models.ImageField(blank=True, upload_to='photos/categories')),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
