# Generated by Django 5.0.2 on 2024-04-05 12:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cartitem_variation_category_cartitem_variation_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='product_price',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
