# Generated by Django 5.0.2 on 2024-03-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_cart_cart_total_cart_coupon_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='copon_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
