# Generated by Django 5.0.2 on 2024-03-10 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_cart_copon_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='copon_code',
            new_name='coupon_code',
        ),
    ]
