# Generated by Django 5.0.2 on 2024-03-12 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_alter_cart_cart_total'),
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='category_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='offers.categoryoffer'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='offers.productoffer'),
        ),
    ]
