# Generated by Django 5.0.2 on 2024-03-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_coupon_discount_alter_order_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='offer_discount_type',
            field=models.CharField(blank=True, choices=[('percentage', 'Percentage'), ('fixed_amount', 'Fixed Amount')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='offer_discount_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='offer_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
